import { slugify } from "./workspace-submission-repository";
import type { AddWorkspaceFormData } from "./types";

export function buildWorkspaceSubmissionPayload(formData: AddWorkspaceFormData, cityId: string | null, userId: string) {
  return {
    name: formData.name,
    type: formData.type,
    city_id: cityId,
    address: formData.address,
    latitude: formData.latitude,
    longitude: formData.longitude,
    location_source: formData.location_source,
    location_provider: formData.location_provider,
    location_provider_id: formData.location_provider_id,
    location_confidence: formData.location_confidence,
    location_raw: formData.location_raw,
    website: formData.website,
    phone: formData.phone,
    description: formData.description,
    short_description: formData.short_description,
    has_wifi: formData.has_wifi,
    wifi_speed: formData.wifi_speed,
    has_power_outlets: formData.has_power_outlets,
    power_outlet_availability: formData.power_outlet_availability,
    seating_capacity: formData.seating_capacity,
    seating_comfort: formData.seating_comfort,
    has_outdoor_seating: formData.has_outdoor_seating,
    has_standing_desks: formData.has_standing_desks,
    noise_level: formData.noise_level,
    has_natural_light: formData.has_natural_light,
    has_air_conditioning: formData.has_air_conditioning,
    has_heating: formData.has_heating,
    music_volume: formData.music_volume,
    has_restrooms: formData.has_restrooms,
    has_parking: formData.has_parking,
    has_bike_parking: formData.has_bike_parking,
    is_accessible: formData.is_accessible,
    allows_pets: formData.allows_pets,
    has_food: formData.has_food,
    has_veg: formData.has_veg,
    has_coffee: formData.has_coffee,
    has_alcohol: formData.has_alcohol,
    price_range: formData.price_range,
    laptop_friendly: formData.laptop_friendly,
    time_limit_hours: formData.time_limit_hours,
    minimum_purchase_required: formData.minimum_purchase_required,
    good_for_meetings: formData.good_for_meetings,
    good_for_calls: formData.good_for_calls,
    good_for_groups: formData.good_for_groups,
    wifi_password_required: false,
    slug: slugify(formData.name),
    submitted_by: userId,
    status: "pending",
  };
}
